### ISSUE TITLE
Suggestion: Add some detailed examples

### ISSUE THREAD

**Issue by willright28** [erthward/geonomics#6]
Hi every authors:

Thanks for developing this very useful and powerful tool in modeling complex landscape genomic, I found it could satisfy my research needs, such as I want to model the effect of different kinds of environmental changes on species. 
But it seems there are no available examples here or on the web [https://geonomics.readthedocs.io/en/latest/index.html](url). Maybe It is difficult for beginners like me to get started.
Hope to see it going on.

Best

**Comment by erthward** [comment]
Hi there!

Thank you. You are completely right! I still need to build some detailed examples into the docs. (I have a placeholder section for this, but have been so busy tying up my dissertation that I have not yet had the time.) That said, a few places to start:
1. [Here](https://geonomics.readthedocs.io/en/latest/intro_video.html)'s a 5-minute intro video that I prepared for the Evolution conference last year.
2. The [demos subdir](https://github.com/erthward/geonomics/tree/main/geonomics/demos) has the code for the three examples published in [the methods paper](https://academic.oup.com/mbe/article/38/10/4634/6297222).
3. This is not officially integrated into the Geonomics docs, but [here](https://github.com/erthward/geonomics_biogeo_demo) is a repo with some code I developed with colleagues, used in a course at Berkeley.
4. If you would like specific support then please feel free to email me with some more details about who you are and what research you are trying to develop. I am happy to help you get up and running, or, if time allows, to talk about the potential to collaborate on a project and provide the simulation code.

I hope that helps!

Drew

**Comment by willright28** [comment]
Hi Drew,
Thanks for your kind reply and instructions.
Please let me email you and I will describe the questions there.

Best!
